module.exports = [
  {
    phone_number: "7890123",
    first_name: "Ella",
    surname: "Martin",
    is_elder: true,
    postcode: "M7 7GG",
    avatar_url: "https://example.com/avatars/ellamartin.jpg",
    profile_msg: "Seeking companionship for walks in the park.",
  },
  {
    phone_number: "8901234",
    first_name: "Michael",
    surname: "Lewis",
    is_elder: false,
    postcode: "M8 8HH",
    avatar_url: "https://example.com/avatars/michaellewis.jpg",
    profile_msg: "I/'m into DIY projects and sharing tips.",
  },
  {
    phone_number: "9012345",
    first_name: "Chloe",
    surname: "White",
    is_elder: false,
    postcode: "M9 9II",
    avatar_url: "https://example.com/avatars/chloewhite.jpg",
    profile_msg: "Offering my services for house-sitting.",
  },
  {
    phone_number: "0123456",
    first_name: "Lucas",
    surname: "Harris",
    is_elder: true,
    postcode: "M10 0JJ",
    avatar_url: "https://example.com/avatars/lucasharris.jpg",
    profile_msg: "Could use some help with household chores.",
  },
  {
    phone_number: "1234568",
    first_name: "Zoe",
    surname: "Clark",
    is_elder: false,
    postcode: "M11 1KK",
    avatar_url: "https://example.com/avatars/zoeclass.jpg",
    profile_msg: "I organize community clean-up events, join us!",
  },
  {
    phone_number: "2345679",
    first_name: "Aiden",
    surname: "Robinson",
    is_elder: false,
    postcode: "M12 2LL",
    avatar_url: "https://example.com/avatars/aidenrobinson.jpg",
    profile_msg: "Photographer available for events and portraits.",
  },
  {
    phone_number: "3456780",
    first_name: "Sophia",
    surname: "Walker",
    is_elder: true,
    postcode: "M13 3MM",
    avatar_url: "https://example.com/avatars/sophiawalker.jpg",
    profile_msg: "Looking for someone to teach me how to use a computer.",
  },
  {
    phone_number: "4567891",
    first_name: "James",
    surname: "Allen",
    is_elder: false,
    postcode: "M14 4NN",
    avatar_url: "https://example.com/avatars/jamesallen.jpg",
    profile_msg: "Volunteering my time for tutoring high school students.",
  },
  {
    phone_number: "5678902",
    first_name: "Grace",
    surname: "Young",
    is_elder: true,
    postcode: "M15 5OO",
    avatar_url: "https://example.com/avatars/graceyoung.jpg",
    profile_msg: "In need of transport to weekly doctor appointments.",
  },
  {
    phone_number: "6789013",
    first_name: "Henry",
    surname: "King",
    is_elder: false,
    postcode: "M16 6PP",
    avatar_url: "https://example.com/avatars/henryking.jpg",
    profile_msg: "Available for pet sitting and care.",
  },
  {
    phone_number: "7890124",
    first_name: "Mia",
    surname: "Thompson",
    is_elder: false,
    postcode: "M17 7QQ",
    avatar_url: "https://example.com/avatars/miathompson.jpg",
    profile_msg: "Enthusiastic about community gardening projects.",
  },
  {
    phone_number: "8901235",
    first_name: "Oliver",
    surname: "Moore",
    is_elder: true,
    postcode: "M18 8RR",
    avatar_url: "https://example.com/avatars/olivermoore.jpg",
    profile_msg: "Looking for help with learning to paint.",
  },
  {
    phone_number: "9012346",
    first_name: "Amelia",
    surname: "Lee",
    is_elder: false,
    postcode: "M19 9SS",
    avatar_url: "https://example.com/avatars/amelialee.jpg",
    profile_msg: "I offer free yoga classes for beginners.",
  },
  {
    phone_number: "0123457",
    first_name: "Ethan",
    surname: "Perez",
    is_elder: false,
    postcode: "M20 0TT",
    avatar_url: "https://example.com/avatars/ethanperez.jpg",
    profile_msg: "Computer whiz looking to help with tech issues.",
  },
  {
    phone_number: "1234569",
    first_name: "Abigail",
    surname: "Davis",
    is_elder: true,
    postcode: "M21 1UU",
    avatar_url: "https://example.com/avatars/abigaildavis.jpg",
    profile_msg: "Seeking assistance with grocery shopping.",
  },
  {
    phone_number: "2345670",
    first_name: "Jackson",
    surname: "Miller",
    is_elder: false,
    postcode: "M22 2VV",
    avatar_url: "https://example.com/avatars/jacksonmiller.jpg",
    profile_msg: "Ready to volunteer for pet rescue services.",
  },
  {
    phone_number: "3456781",
    first_name: "Madison",
    surname: "Anderson",
    is_elder: false,
    postcode: "M23 3WW",
    avatar_url: "https://example.com/avatars/madisonanderson.jpg",
    profile_msg: "Graphic designer offering free workshops for teens.",
  },
  {
    phone_number: "4567892",
    first_name: "Logan",
    surname: "Taylor",
    is_elder: true,
    postcode: "M24 4XX",
    avatar_url: "https://example.com/avatars/logantaylor.jpg",
    profile_msg: "Would appreciate help with garden maintenance.",
  },
  {
    phone_number: "5678903",
    first_name: "Sophie",
    surname: "Hernandez",
    is_elder: true,
    postcode: "M25 5YY",
    avatar_url: "https://example.com/avatars/sophiehernandez.jpg",
    profile_msg: "Im looking to learn new crafts, any teachers out there?",
  },
  {
    phone_number: "6789014",
    first_name: "Benjamin",
    surname: "Martinez",
    is_elder: false,
    postcode: "M26 6ZZ",
    avatar_url: "https://example.com/avatars/benjaminmartinez.jpg",
    profile_msg: "Join me for weekend cycling and adventure.",
  },
];
